### ISSUE TITLE
Success rate?

### ISSUE THREAD

**Issue by chandraaditya** [janghaludu/cowin-captcha#1]
Hey, I was wondering what success rate you're getting? 🤔 I'm not planning on building a bot dw lol, just curious.

**Comment by janghaludu** [comment]
Pretty decent surprisingly. I didn't run any elaborate tests but noticed it to be around 95% at character level

**Comment by chandraaditya** [comment]
Oh wow not bad

**Comment by janghaludu** [comment]
Managed to hit most definitely 100% thanks to @subhashisbhowmik 's tip at #2  Used a cunning hack to label all images accurately first and used a descriptor that is sensitive to size and orientation.Yet to see a wrong result in my tests for about 500 consecutive images / 2500 characters :)
